.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml

This reverts commit 9729a9178f6b88b3265ee24032ed33093afe20c8.

Revert commit 9729a9178f6b88b3265ee24032ed33093afe20c8

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml

Deploying AL-Go from main (cd65fef534b14be11e4d0e3c9905869fad786d36) to preview

Deploying AL-Go from main (cd65fef534b14be11e4d0e3c9905869fad786d36) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
SECURITY.md
SUPPORT.md

Deploying AL-Go from main (eabe480ba72260c6805e575f6bd03ac129367160) to preview

Deploying AL-Go from main (eabe480ba72260c6805e575f6bd03ac129367160) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml

Deploying AL-Go from main (13989cd251c3eddc64f3603248f6148619ecd88e) to preview

Deploying AL-Go from main (13989cd251c3eddc64f3603248f6148619ecd88e) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml

Deploying AL-Go from main (56073be9af4a2a78a21f96ef120870ab688004ca) to preview

Deploying AL-Go from main (56073be9af4a2a78a21f96ef120870ab688004ca) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml

Deploying AL-Go from main (31be77d8466260c22e324516ec543285e6dfc521) to preview

Deploying AL-Go from main (31be77d8466260c22e324516ec543285e6dfc521) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml

Deploying AL-Go from main (7839c2380d659b294268251d23c2643c6bf067d7) to preview

Deploying AL-Go from main (7839c2380d659b294268251d23c2643c6bf067d7) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml

Deploying AL-Go from main (ce6a36367580e96a44bbc3b5dd31238d945cf8fe) to preview

Deploying AL-Go from main (ce6a36367580e96a44bbc3b5dd31238d945cf8fe) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml

Deploying AL-Go from main (d9d3b069e8e3d8891a3602a75e3261d85d8f4555) to preview

Deploying AL-Go from main (d9d3b069e8e3d8891a3602a75e3261d85d8f4555) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
CODEOWNERS
SECURITY.md
SUPPORT.md

Deploying AL-Go from main (37e4e3fac9276ad13dc998d03f7bf0fdad577d19) to v3.3

Deploying AL-Go from main (37e4e3fac9276ad13dc998d03f7bf0fdad577d19) to v3.3

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml

Deploying AL-Go from main (37e4e3fac9276ad13dc998d03f7bf0fdad577d19) to preview

Deploying AL-Go from main (37e4e3fac9276ad13dc998d03f7bf0fdad577d19) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
CODEOWNERS
SECURITY.md
SUPPORT.md

Deploying AL-Go from main (37e4e3fac9276ad13dc998d03f7bf0fdad577d19) to main

Deploying AL-Go from main (37e4e3fac9276ad13dc998d03f7bf0fdad577d19) to main

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/Test Next Major.settings.json
.github/Test Next Minor.settings.json
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml

Deploying AL-Go from main (54737c26ba5d1c8b647c089a372d9cd2cd907365) to preview

Deploying AL-Go from main (54737c26ba5d1c8b647c089a372d9cd2cd907365) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml

Deploying AL-Go from main (460e5582330ac797f44075a61407fe830967ceac) to preview

Deploying AL-Go from main (460e5582330ac797f44075a61407fe830967ceac) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml

Deploying AL-Go from main (31944622373d473cf9b727a320333e170290265b) to preview

Deploying AL-Go from main (31944622373d473cf9b727a320333e170290265b) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml

Deploying AL-Go from main (6bbfb2b86c33a979e556a96d1510e8e17dbb8ec3) to preview

Deploying AL-Go from main (6bbfb2b86c33a979e556a96d1510e8e17dbb8ec3) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/Test Next Major.settings.json
.github/Test Next Minor.settings.json
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml

Deploying AL-Go from main (91a563be484eeff8ccde7f39b3622991cc8931f0) to v4.0

Deploying AL-Go from main (91a563be484eeff8ccde7f39b3622991cc8931f0) to v4.0

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml

Deploying AL-Go from main (91a563be484eeff8ccde7f39b3622991cc8931f0) to preview

Deploying AL-Go from main (91a563be484eeff8ccde7f39b3622991cc8931f0) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.gitignore

Deploying AL-Go from main (4aa78c89b0c0c3a54c38d2815dfae789239db8b7) to preview

Deploying AL-Go from main (4aa78c89b0c0c3a54c38d2815dfae789239db8b7) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml

Deploying AL-Go from main (fc491ffce4cc911d677b3b4318a9372fbe54141e) to preview

Deploying AL-Go from main (fc491ffce4cc911d677b3b4318a9372fbe54141e) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml

Deploying AL-Go from main (e55c2d0f72a93c8ef9aac8d3180e2fffc8d5695b) to preview

Deploying AL-Go from main (e55c2d0f72a93c8ef9aac8d3180e2fffc8d5695b) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.gitignore

Deploying AL-Go from main (ad7ba196b05948c0f3522a1dea60916df5169f00) to v4.1

Deploying AL-Go from main (ad7ba196b05948c0f3522a1dea60916df5169f00) to v4.1

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.gitignore

Deploying AL-Go from main (ad7ba196b05948c0f3522a1dea60916df5169f00) to main

Deploying AL-Go from main (ad7ba196b05948c0f3522a1dea60916df5169f00) to main

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml

Deploying AL-Go from main (ddd94d3927e14dff2b45f9907f245513d202d8f4) to preview

Deploying AL-Go from main (ddd94d3927e14dff2b45f9907f245513d202d8f4) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml

Deploying AL-Go from main (4c5bfbca1adebbf997f63882df4b9074a19aac1d) to preview

Deploying AL-Go from main (4c5bfbca1adebbf997f63882df4b9074a19aac1d) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml

Deploying AL-Go from main (8dfde66bdf7b91d0d56d9a97f6f1688e444e067d) to preview

Deploying AL-Go from main (8dfde66bdf7b91d0d56d9a97f6f1688e444e067d) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml

Deploying AL-Go from main (d0a5de49086c1abf25bfc3dc4ac3e931e66f5bd4) to preview

Deploying AL-Go from main (d0a5de49086c1abf25bfc3dc4ac3e931e66f5bd4) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml

Deploying AL-Go from main (e6f32930d61ce5fbf63e9567ee61492bb0ce0690) to v5.0

Deploying AL-Go from main (e6f32930d61ce5fbf63e9567ee61492bb0ce0690) to v5.0

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml

Deploying AL-Go from main (e6f32930d61ce5fbf63e9567ee61492bb0ce0690) to preview

Deploying AL-Go from main (e6f32930d61ce5fbf63e9567ee61492bb0ce0690) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml

Deploying AL-Go from main (e6f32930d61ce5fbf63e9567ee61492bb0ce0690) to main

Deploying AL-Go from main (e6f32930d61ce5fbf63e9567ee61492bb0ce0690) to main

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml

Deploying AL-Go from main (f6bfb8fa422ba66412aea71cf1e396b0f3032ff4) to preview

Deploying AL-Go from main (f6bfb8fa422ba66412aea71cf1e396b0f3032ff4) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml

Deploying AL-Go from main (3275712f682a1301dca1ff9c3d9abb5c7d2e6840) to preview

Deploying AL-Go from main (3275712f682a1301dca1ff9c3d9abb5c7d2e6840) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml

Deploying AL-Go from main (f2f452940bc16f36a4c59f1fd1982c566f16c03c) to preview

Deploying AL-Go from main (f2f452940bc16f36a4c59f1fd1982c566f16c03c) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml

Deploying AL-Go from main (dd5c9ebf4bd06d33d45a26aa2fb3d0620277b1d0) to preview

Deploying AL-Go from main (dd5c9ebf4bd06d33d45a26aa2fb3d0620277b1d0) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml

Deploying AL-Go from main (92365fbce2f60a8b26758608f36f9e24265646d4) to v5.1

Deploying AL-Go from main (92365fbce2f60a8b26758608f36f9e24265646d4) to v5.1

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml

Deploying AL-Go from main (92365fbce2f60a8b26758608f36f9e24265646d4) to main

Deploying AL-Go from main (92365fbce2f60a8b26758608f36f9e24265646d4) to main

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullPowerPlatformChanges.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/PushPowerPlatformChanges.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.github/workflows/_BuildPowerPlatformSolution.yaml

Deploying AL-Go from main (6a9ef0c91e5b54d0fd3abb3d4495417a1db28f17) to preview

Deploying AL-Go from main (6a9ef0c91e5b54d0fd3abb3d4495417a1db28f17) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullPowerPlatformChanges.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/PushPowerPlatformChanges.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.github/workflows/_BuildPowerPlatformSolution.yaml

Deploying AL-Go from main (383330241ad5197bb44396441a2a5ace0c879d1f) to v5.2

Deploying AL-Go from main (383330241ad5197bb44396441a2a5ace0c879d1f) to v5.2

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullPowerPlatformChanges.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/PushPowerPlatformChanges.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.github/workflows/_BuildPowerPlatformSolution.yaml

Deploying AL-Go from main (383330241ad5197bb44396441a2a5ace0c879d1f) to preview

Deploying AL-Go from main (383330241ad5197bb44396441a2a5ace0c879d1f) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullPowerPlatformChanges.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/PushPowerPlatformChanges.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.github/workflows/_BuildPowerPlatformSolution.yaml

Deploying AL-Go from main (383330241ad5197bb44396441a2a5ace0c879d1f) to main

Deploying AL-Go from main (383330241ad5197bb44396441a2a5ace0c879d1f) to main

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullPowerPlatformChanges.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/PushPowerPlatformChanges.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.github/workflows/_BuildPowerPlatformSolution.yaml
README.md
SECURITY.md

Deploying AL-Go from main (3ecb65a53dfa9187e7b329bebdc443e42c6dde51) to preview

Deploying AL-Go from main (3ecb65a53dfa9187e7b329bebdc443e42c6dde51) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullPowerPlatformChanges.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/PushPowerPlatformChanges.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.github/workflows/_BuildPowerPlatformSolution.yaml
README.md

Deploying AL-Go from main (5eeeec54ab7e6a9d97701effe420ef74bda08c67) to preview

Deploying AL-Go from main (5eeeec54ab7e6a9d97701effe420ef74bda08c67) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullPowerPlatformChanges.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/PushPowerPlatformChanges.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.github/workflows/_BuildPowerPlatformSolution.yaml

Deploying AL-Go from main (fa90994cf0e9dbf357a5316bc079e252fe73b581) to preview

Deploying AL-Go from main (fa90994cf0e9dbf357a5316bc079e252fe73b581) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullPowerPlatformChanges.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/PushPowerPlatformChanges.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.github/workflows/_BuildPowerPlatformSolution.yaml

Deploying AL-Go from main (381a1e2d859ecafd242ca80a45449caf3c8b7fd5) to preview

Deploying AL-Go from main (381a1e2d859ecafd242ca80a45449caf3c8b7fd5) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullPowerPlatformChanges.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/PushPowerPlatformChanges.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.github/workflows/_BuildPowerPlatformSolution.yaml

Deploying AL-Go from main (6e2d05ca0fcb62e51e403cbd0539c6b1ad7f3080) to preview

Deploying AL-Go from main (6e2d05ca0fcb62e51e403cbd0539c6b1ad7f3080) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullPowerPlatformChanges.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/PushPowerPlatformChanges.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.github/workflows/_BuildPowerPlatformSolution.yaml

Deploying AL-Go from main (75ef430ead72a4c0c4753fb328ecf0257c20c510) to preview

Deploying AL-Go from main (75ef430ead72a4c0c4753fb328ecf0257c20c510) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullPowerPlatformChanges.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/PushPowerPlatformChanges.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.github/workflows/_BuildPowerPlatformSolution.yaml
README.md
SECURITY.md

Deploying AL-Go from main (a2c4efcc730e9b264f74cb321e7c2193c8c96b8d) to v5.3

Deploying AL-Go from main (a2c4efcc730e9b264f74cb321e7c2193c8c96b8d) to v5.3

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullPowerPlatformChanges.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/PushPowerPlatformChanges.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.github/workflows/_BuildPowerPlatformSolution.yaml

Deploying AL-Go from main (a2c4efcc730e9b264f74cb321e7c2193c8c96b8d) to preview

Deploying AL-Go from main (a2c4efcc730e9b264f74cb321e7c2193c8c96b8d) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullPowerPlatformChanges.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/PushPowerPlatformChanges.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.github/workflows/_BuildPowerPlatformSolution.yaml
README.md
SECURITY.md

Deploying AL-Go from main (a2c4efcc730e9b264f74cb321e7c2193c8c96b8d) to main

Deploying AL-Go from main (a2c4efcc730e9b264f74cb321e7c2193c8c96b8d) to main

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullPowerPlatformChanges.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/PushPowerPlatformChanges.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.github/workflows/_BuildPowerPlatformSolution.yaml

Deploying AL-Go from main (564c339085ae0ffa74c5bde71c15fea7fe54bbf1) to preview

Deploying AL-Go from main (564c339085ae0ffa74c5bde71c15fea7fe54bbf1) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullPowerPlatformChanges.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/PushPowerPlatformChanges.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.github/workflows/_BuildPowerPlatformSolution.yaml

Deploying AL-Go from main (a2a51be438318a7e355fa9044815cf7890ffed1a) to preview

Deploying AL-Go from main (a2a51be438318a7e355fa9044815cf7890ffed1a) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullPowerPlatformChanges.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/PushPowerPlatformChanges.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.github/workflows/_BuildPowerPlatformSolution.yaml

Deploying AL-Go from main (6d6292c0fc1295bccd0ec2e91a916bce02210d0f) to main

Deploying AL-Go from main (6d6292c0fc1295bccd0ec2e91a916bce02210d0f) to main

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullPowerPlatformChanges.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/PushPowerPlatformChanges.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.github/workflows/_BuildPowerPlatformSolution.yaml

Deploying AL-Go from main (6d6292c0fc1295bccd0ec2e91a916bce02210d0f) to preview

Deploying AL-Go from main (6d6292c0fc1295bccd0ec2e91a916bce02210d0f) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullPowerPlatformChanges.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/PushPowerPlatformChanges.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.github/workflows/_BuildPowerPlatformSolution.yaml

Deploying AL-Go from main (6d6292c0fc1295bccd0ec2e91a916bce02210d0f) to v6.0

Deploying AL-Go from main (6d6292c0fc1295bccd0ec2e91a916bce02210d0f) to v6.0

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullPowerPlatformChanges.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/PushPowerPlatformChanges.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.github/workflows/_BuildPowerPlatformSolution.yaml

Deploying AL-Go from main (a46044fa1ffca4b1ff05d2d1844fd7d5922c6984) to preview

Deploying AL-Go from main (a46044fa1ffca4b1ff05d2d1844fd7d5922c6984) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullPowerPlatformChanges.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/PushPowerPlatformChanges.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.github/workflows/_BuildPowerPlatformSolution.yaml

Deploying AL-Go from main (a1290fdde01396f3dad78d0c593af9b4d36af1ec) to v6.1

Deploying AL-Go from main (a1290fdde01396f3dad78d0c593af9b4d36af1ec) to v6.1

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullPowerPlatformChanges.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/PushPowerPlatformChanges.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.github/workflows/_BuildPowerPlatformSolution.yaml

Deploying AL-Go from main (a1290fdde01396f3dad78d0c593af9b4d36af1ec) to preview

Deploying AL-Go from main (a1290fdde01396f3dad78d0c593af9b4d36af1ec) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullPowerPlatformChanges.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/PushPowerPlatformChanges.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.github/workflows/_BuildPowerPlatformSolution.yaml

Deploying AL-Go from main (a1290fdde01396f3dad78d0c593af9b4d36af1ec) to main

Deploying AL-Go from main (a1290fdde01396f3dad78d0c593af9b4d36af1ec) to main

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullPowerPlatformChanges.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/PushPowerPlatformChanges.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.github/workflows/_BuildPowerPlatformSolution.yaml

Deploying AL-Go from main (9dbee17f636ca9ba2649b45adc2b65f4fd66af84) to preview

Deploying AL-Go from main (9dbee17f636ca9ba2649b45adc2b65f4fd66af84) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullPowerPlatformChanges.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/PushPowerPlatformChanges.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.github/workflows/_BuildPowerPlatformSolution.yaml

Deploying AL-Go from main (006019b87cab11f6234d05f2c34372daf3c7075d) to preview

Deploying AL-Go from main (006019b87cab11f6234d05f2c34372daf3c7075d) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullPowerPlatformChanges.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/PushPowerPlatformChanges.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.github/workflows/_BuildPowerPlatformSolution.yaml

Deploying AL-Go from main (86403d92a5e431a1146dafd38d4df17ea153ebaf) to v6.2

Deploying AL-Go from main (86403d92a5e431a1146dafd38d4df17ea153ebaf) to v6.2

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullPowerPlatformChanges.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/PushPowerPlatformChanges.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.github/workflows/_BuildPowerPlatformSolution.yaml

Deploying AL-Go from main (86403d92a5e431a1146dafd38d4df17ea153ebaf) to preview

Deploying AL-Go from main (86403d92a5e431a1146dafd38d4df17ea153ebaf) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullPowerPlatformChanges.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/PushPowerPlatformChanges.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.github/workflows/_BuildPowerPlatformSolution.yaml

Deploying AL-Go from main (86403d92a5e431a1146dafd38d4df17ea153ebaf) to main

Deploying AL-Go from main (86403d92a5e431a1146dafd38d4df17ea153ebaf) to main

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullPowerPlatformChanges.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/PushPowerPlatformChanges.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.github/workflows/_BuildPowerPlatformSolution.yaml

Deploying AL-Go from main (471b88b68863d06568efb833d74b02f0879b1c89) to preview

Deploying AL-Go from main (471b88b68863d06568efb833d74b02f0879b1c89) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullPowerPlatformChanges.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/PushPowerPlatformChanges.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.github/workflows/_BuildPowerPlatformSolution.yaml
SECURITY.md

Deploying AL-Go from main (44100a28d57e2c582859205900ac519d9d76c57c) to preview

Deploying AL-Go from main (44100a28d57e2c582859205900ac519d9d76c57c) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullPowerPlatformChanges.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/PushPowerPlatformChanges.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.github/workflows/_BuildPowerPlatformSolution.yaml

Deploying AL-Go from main (1c9e7141ae2b09165f864c64912ead99b9aab55c) to preview

Deploying AL-Go from main (1c9e7141ae2b09165f864c64912ead99b9aab55c) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullPowerPlatformChanges.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/PushPowerPlatformChanges.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.github/workflows/_BuildPowerPlatformSolution.yaml

Deploying AL-Go from main (bdca9f401495268cb0548da3379efa0d2b4c85b2) to preview

Deploying AL-Go from main (bdca9f401495268cb0548da3379efa0d2b4c85b2) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullPowerPlatformChanges.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/PushPowerPlatformChanges.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.github/workflows/_BuildPowerPlatformSolution.yaml

Deploying AL-Go from main (120540b15626528818b0aca52dc4822eb527e5c4) to preview

Deploying AL-Go from main (120540b15626528818b0aca52dc4822eb527e5c4) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullPowerPlatformChanges.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/PushPowerPlatformChanges.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.github/workflows/_BuildPowerPlatformSolution.yaml
SECURITY.md

Deploying AL-Go from main (120540b15626528818b0aca52dc4822eb527e5c4) to main

Deploying AL-Go from main (120540b15626528818b0aca52dc4822eb527e5c4) to main

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullPowerPlatformChanges.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/PushPowerPlatformChanges.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.github/workflows/_BuildPowerPlatformSolution.yaml
SECURITY.md

Deploying AL-Go from main (120540b15626528818b0aca52dc4822eb527e5c4) to v6.3

Deploying AL-Go from main (120540b15626528818b0aca52dc4822eb527e5c4) to v6.3

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullPowerPlatformChanges.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/PushPowerPlatformChanges.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.github/workflows/_BuildPowerPlatformSolution.yaml

Deploying AL-Go from main (b8d327e7c8110b8a19a48d4e84756fd5d9222136) to preview

Deploying AL-Go from main (b8d327e7c8110b8a19a48d4e84756fd5d9222136) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullPowerPlatformChanges.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/PushPowerPlatformChanges.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.github/workflows/_BuildPowerPlatformSolution.yaml

Deploying AL-Go from main (7c4fec6c2547eee4eb1db58a1d52076dcda88ce2) to preview

Deploying AL-Go from main (7c4fec6c2547eee4eb1db58a1d52076dcda88ce2) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullPowerPlatformChanges.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/PushPowerPlatformChanges.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.github/workflows/_BuildPowerPlatformSolution.yaml

Deploying AL-Go from main (98de5bf31c06a3bff621c640bdfbe7853f9f54c9) to preview

Deploying AL-Go from main (98de5bf31c06a3bff621c640bdfbe7853f9f54c9) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullPowerPlatformChanges.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/PushPowerPlatformChanges.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.github/workflows/_BuildPowerPlatformSolution.yaml

Deploying AL-Go from main (aca0ff0e870719bcda2f36bcdfe2109ce04b32ce) to preview

Deploying AL-Go from main (aca0ff0e870719bcda2f36bcdfe2109ce04b32ce) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullPowerPlatformChanges.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/PushPowerPlatformChanges.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.github/workflows/_BuildPowerPlatformSolution.yaml

Deploying AL-Go from main (41a2375645046812eb93fd5a67b5e0dd4a4438a1) to preview

Deploying AL-Go from main (41a2375645046812eb93fd5a67b5e0dd4a4438a1) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullPowerPlatformChanges.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/PushPowerPlatformChanges.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.github/workflows/_BuildPowerPlatformSolution.yaml

Deploying AL-Go from main (4dd210d3d780decee8e8b858fe216e559f7ce2bc) to preview

Deploying AL-Go from main (4dd210d3d780decee8e8b858fe216e559f7ce2bc) to preview

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullPowerPlatformChanges.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/PushPowerPlatformChanges.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.github/workflows/_BuildPowerPlatformSolution.yaml

Deploying AL-Go from main (4000fc21109200985749fbbb6b62d22d20a8adcb) to main

Deploying AL-Go from main (4000fc21109200985749fbbb6b62d22d20a8adcb) to main

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/AL-Go-Settings.json
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullPowerPlatformChanges.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/PushPowerPlatformChanges.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.github/workflows/_BuildPowerPlatformSolution.yaml

Deploying AL-Go from main (4000fc21109200985749fbbb6b62d22d20a8adcb) to v6.4

Deploying AL-Go from main (4000fc21109200985749fbbb6b62d22d20a8adcb) to v6.4

---

.AL-Go/cloudDevEnv.ps1
.AL-Go/localDevEnv.ps1
.github/RELEASENOTES.copy.md
.github/workflows/AddExistingAppOrTestApp.yaml
.github/workflows/CICD.yaml
.github/workflows/CreateApp.yaml
.github/workflows/CreateOnlineDevelopmentEnvironment.yaml
.github/workflows/CreatePerformanceTestApp.yaml
.github/workflows/CreateRelease.yaml
.github/workflows/CreateTestApp.yaml
.github/workflows/Current.yaml
.github/workflows/DeployReferenceDocumentation.yaml
.github/workflows/IncrementVersionNumber.yaml
.github/workflows/NextMajor.yaml
.github/workflows/NextMinor.yaml
.github/workflows/PublishToEnvironment.yaml
.github/workflows/PullPowerPlatformChanges.yaml
.github/workflows/PullRequestHandler.yaml
.github/workflows/PushPowerPlatformChanges.yaml
.github/workflows/Troubleshooting.yaml
.github/workflows/UpdateGitHubGoSystemFiles.yaml
.github/workflows/_BuildALGoProject.yaml
.github/workflows/_BuildPowerPlatformSolution.yaml

Deploying AL-Go from main (2446afd384183125d93a07d8cb040e6bdd3987f6) to preview

Deploying AL-Go from main (2446afd384183125d93a07d8cb040e6bdd3987f6) to preview
